version: '2.1'
orbs:
  vuln-scan: zt-cci-orb/zt-cci-orb@0.0.4
workflows:
  zerothreat-security-scan:
    jobs:
      - vuln-scan/scan-job:
          ZT_TOKEN: "M9MT6E7Z3722.M9MT6E7Z4788"
          WAIT_FOR_ANALYSIS: true
